#!/bin/bash

# Instal Step #2: In Chroot
# Now setup our fresh-instlled Arch Linux!


# Time zone

echo '> Now is setup my timezone..'
ln -svf /usr/share/zoneinfo/Asia/Yekaterinburg /etc/localtime



# Localization

echo '> Setup EN/RU language support...'
echo "en_US.UTF-8 UTF-8" > /etc/locale.gen
echo "ru_RU.UTF-8 UTF-8" >> /etc/locale.gen

echo '> Refresh locale in the system...'
locale-gen

echo '> Setup system default language'
echo 'LANG="en_US.UTF-8"' >> /etc/locale.conf

echo '> Setup RU language for console'
echo 'KEYMAP=ru' >> /etc/vconsole.conf
echo 'FONT=cyr-sun16' >> /etc/vconsole.conf



# Network configuration

echo '> Setup a hostname for the machine...'
echo "observer" > /etc/hostname

echo '> Enable NerworkManager'
systemctl enable NetworkManager



# Initramfs

echo '> Init RAM FS...'
mkinitcpio -p linux



# Root password

echo '>> Choose a root user password:'
passwd



# Mircocode
# Already installed for AMD only! Info: https://wiki.archlinux.org/index.php/Microcode


# GRUB

echo '> Install GRUB loader to disk...'
grub-install --target=i386-pc /dev/sda

echo '> Make GRUB config...'
grub-mkconfig -o /boot/grub/grub.cfg

echo 'Enable multilib repo for run 32-bit applications on x64 system...'
echo '[multilib]' >> /etc/pacman.conf
echo 'Include = /etc/pacman.d/mirrorlist' >> /etc/pacman.conf
pacman -Syy

echo '>>> Reboot...'
exit
read -p "Pause 3 seconds..." -t 3
reboot
